export const OutcomeCategory = {
  SUCCESS: 'SUCCESS',
  CONFIG_ERROR: 'CONFIG_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  INCOMPATIBLE: 'INCOMPATIBLE',
  NOT_FOUND: 'NOT_FOUND',
  TRANSIENT_OUTAGE: 'TRANSIENT_OUTAGE',
  MUTATION_VIOLATION: 'MUTATION_VIOLATION',
  CORRUPTION: 'CORRUPTION',
  CONFLICT: 'CONFLICT',
} as const;

export type OutcomeCategory = (typeof OutcomeCategory)[keyof typeof OutcomeCategory];

export const EXIT_CODES: Record<OutcomeCategory, number> = {
  SUCCESS: 0,
  CONFIG_ERROR: 1,
  AUTHENTICATION_ERROR: 2,
  INCOMPATIBLE: 3,
  NOT_FOUND: 4,
  TRANSIENT_OUTAGE: 5,
  MUTATION_VIOLATION: 6,
  CORRUPTION: 7,
  CONFLICT: 8,
};
